"""empty message

Revision ID: 5349adcee108
Revises: 
Create Date: 2023-01-27 23:09:29.603471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5349adcee108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diccionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_situacion', sa.String(length=120), nullable=False),
    sa.Column('url_img', sa.String(length=120), nullable=False),
    sa.Column('url_video', sa.String(length=120), nullable=False),
    sa.Column('tipo_url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_situacion'),
    sa.UniqueConstraint('tipo_url'),
    sa.UniqueConstraint('url_img'),
    sa.UniqueConstraint('url_video')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('fullname', sa.String(length=80), nullable=False),
    sa.Column('address1', sa.String(length=80), nullable=False),
    sa.Column('address2', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('npostal', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('me_gusta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_diccionario', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_diccionario'], ['diccionario.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('me_gusta')
    op.drop_table('user')
    op.drop_table('diccionario')
    # ### end Alembic commands ###
